version: '3.8'

services:
  discord-bot:
    build:
      context: .
    env_file: .env
    image: discord-bot:latest
    container_name: discord-bot
    restart: unless-stopped
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge
