version: '3.8'

services:
  discord-bot:
    build: .
    image: jcukier/discord-bot:latest
    container_name: discord-bot
    restart: unless-stopped
    env_file: .env
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge
