name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  go-cicd:
    # Ensure binary builds and tests pass successfully
    uses: ./.github/workflows/go_cicd.yaml

  docker-cicd:
    # Only build and deploy Docker image if go-cicd job succeeded
    needs: go-cicd
    uses: ./.github/workflows/docker_cicd.yaml
