name: Test Deploy Pipeline

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  go-cicd:
    uses: ./.github/workflows/go-cicd.yaml

  docker-cicd:
    needs: go-cicd
    uses: ./.github/workflows/docker-cicd.yaml
    with:
      version: 0.0.${{ github.event.pull_request.number }}
    secrets: inherit

  deploy:
    needs: docker-cicd
    uses: ./.github/workflows/deploy-cicd.yaml
    with:
      version: 0.0.${{ github.event.pull_request.number }}
    secrets: inherit
