name: Test Deploy CI/CD

on:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  test-deploy:
    uses: ./.github/workflows/deploy-cicd.yaml
    with:
      docker_image: ${{ vars.DOCKER_IMAGE }}
    secrets: inherit
